stages:
    - build
    - deploy
    - release

variables:
    QGIS_FLAVOR: ltr        

build:
  stage: build
  script:
    - make build deliver clean FLAVOR=$QGIS_FLAVOR
  environment:
    name: snap
  artifacts:
    paths:
      - factory.manifest
  tags:
    - infrav3

deploy_snap:
  stage: deploy
  script:
    - $HOME/bin/lzmservicectl update -C MUTU wps --annotate="Updated image $QGIS_FLAVOR ($CI_COMMIT_SHORT_SHA)"
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh --clean
  environment:
    name: snap
  tags:
    - infrav3

# Make release job target visible on gitlab
release:ltr:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh qgis-wps-server-$QGIS_FLAVOR
  environment:
    name: production
  when: manual
  only:
    variables:
      - $QGIS_FLAVOR == "ltr"
  tags:
    - infrav3

# Make release job target visible on gitlab
release:release:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh qgis-wps-server-$QGIS_FLAVOR
  environment:
    name: production
  when: manual
  only:
    variables:
      - $QGIS_FLAVOR == "release"
  tags:
    - infrav3

